version: "3.8"

services:
  sentry:
    container_name: sentry
    image: node:22.3.0
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    command: sh -c "yarn add sharp --ignore-engines && yarn dev"